DROP SCHEMA IF EXISTS FOREST;
CREATE SCHEMA FOREST;
USE FOREST;

-- TABELA USUÁRIOS

DROP TABLE USUARIO;
CREATE TABLE USUARIO (ID INT,
					   USERNAME VARCHAR(100),
                       EMAIL VARCHAR (100),
                       MOEDAS INT,
                       CRISTAIS INT,
                       ARVORES_REAL INT);
                       
-- TABELA ÁRVORES

DROP TABLE ARVORE;
CREATE TABLE ARVORE (ID INT,
					NOME VARCHAR(100));
                    
-- TABELA TAGS

DROP TABLE TAG;
CREATE TABLE TAG (ID INT,
					NOME VARCHAR(100),
                    COR VARCHAR(10));
                    
-- TABELA CONQUISTAS

DROP TABLE CONQUISTA;
CREATE TABLE CONQUISTA (ID INT,
					NOME VARCHAR(100),
                    DESCRIÇÃO VARCHAR (100),
                    DESBLOQUEADO BOOLEAN);     
                    

-- TABELA DA LOJA 

DROP TABLE LOJA;
CREATE TABLE LOJA (ID INT,
					ARVORE VARCHAR(100),
                    MOEDAS INT,
                    DESBLOQUEADA BOOLEAN);
                       
                       
                       
                       
                       
-- INSERIR USUÁRIOS

INSERT INTO USUARIO VALUES (1, 'KEVIN', 'KEVIN@EMAIL.COM', 940, 0 , 2);
INSERT INTO USUARIO VALUES (2, 'TIFFANY', 'TIFFANY@EMAIL.COM', 300, 0, 1);
INSERT INTO USUARIO VALUES (3, 'HENRY', 'HENRY@EMAIL.COM', 500, 0, 3);
INSERT INTO USUARIO VALUES (4, 'JAMES', 'JAMES@EMAIL.COM', 200, 0, 2);
INSERT INTO USUARIO VALUES (5, 'AMANDA', 'AMANDA@EMAIL.COM', 400, 0, 5);
INSERT INTO USUARIO VALUES (6, 'ANTON', 'ANTON@EMAIL.COM', 300, 0, 1);
INSERT INTO USUARIO VALUES (7, 'JIN', 'JIN@EMAIL.COM', 100, 0, 4);
INSERT INTO USUARIO VALUES (8, 'MARK', 'MARK@EMAIL.COM', 800, 100, 1);
INSERT INTO USUARIO VALUES (9, 'MARTA', 'MARTA@EMAIL.COM', 400, 0, 3);
INSERT INTO USUARIO VALUES (10, 'OLIVIA', 'OLIVIA@EMAIL.COM', 100, 0, 2);
                       
SELECT * FROM USUARIO;

-- INSERIR ÁRVORES

INSERT INTO ARVORE VALUES (1, 'PINHEIRO');
INSERT INTO ARVORE VALUES (2, 'MAPLE');
INSERT INTO ARVORE VALUES (3, 'CELESTIAL');
INSERT INTO ARVORE VALUES (4, 'BAMBOO');
INSERT INTO ARVORE VALUES (5, 'CACTUS');
INSERT INTO ARVORE VALUES (6, 'JARACANDA');

 SELECT * FROM ARVORE;                      
							
-- INSERIR TAGS

INSERT INTO TAG VALUES (1, 'ESTUDO', 'AZUL');
INSERT INTO TAG VALUES (2, 'LEITURA', 'VERDE');
INSERT INTO TAG VALUES (3, 'PINTURA', 'ROSA');
INSERT INTO TAG VALUES (4, 'TRABALHO', 'LILÁS');
INSERT INTO TAG VALUES (5, 'GINÁSTICA', 'VERMLHO');

SELECT * FROM TAG;

-- INSERIR CONQUISTAS

INSERT INTO CONQUISTA VALUES (1, '3 DIAS NA LINHA', 'PLANTAR POR 3 DIAS SEGUIDOS', TRUE);
INSERT INTO CONQUISTA VALUES (2, '7 DIAS NA LINHA', 'PLANTAR POR 7 DIAS SEGUIDOS', TRUE);
INSERT INTO CONQUISTA VALUES (3, '15 DIAS NA LINHA', 'PLANTAR POR 15 DIAS SEGUIDOS', FALSE);
INSERT INTO CONQUISTA VALUES (4, 'PLANTANDO EM GRUOPO', 'ADICIONAR 5 AMIGOS', TRUE);
INSERT INTO CONQUISTA VALUES (5, 'BOTÂNICO', 'DESBLOQUEIE 3 ESPÉCIES DE ÁRVORES' , FALSE);

SELECT * FROM CONQUISTA;

-- INSERIR LOJA

INSERT INTO LOJA VALUES (1, 'CELESTIAL', 2000, TRUE);
INSERT INTO LOJA VALUES (2, 'MAPLE', 2000, TRUE);
INSERT INTO LOJA VALUES (3, 'BAMBOO', 1200, FALSE);
INSERT INTO LOJA VALUES (4, 'CACTUS', 1200, FALSE);
INSERT INTO LOJA VALUES (5, 'JACARANDA', 1200, FALSE);

SELECT * FROM LOJA;
